### ISSUE TITLE
autoSaveTime does not work with PNG & JPG

### ISSUE THREAD

**Issue by lejeunerenard** [spite/ccapture.js#37]
When trying to use the `autoSaveTime` parameter (set to `5`) with the JPG encoder, it did not automatically save the frames.

There is a vestigial fragment of a previous implementation commented out on this line [here]( https://github.com/spite/ccapture.js/blob/master/src/CCapture.js#L192). Was `autoSaveTime` removed intentionally for PNG & JPG encoders? If not, I can take a stab at reimplementing it.

**Comment by spite** [comment]
Good question! It might be that saving closed the tape, or something like that. I added the autoSave option because the webm recorder made the browser crash with long/big videos, as a solution to save pieces that could be salvaged if that happened.

It should be easy to add (or enable again). If you need it, and want to take a look, you're more than welcome!

**Comment by renambot-uic** [comment]
Any progress on this ?

**Comment by lejeunerenard** [comment]
@renambot-uic nope. I did a quick fix that made it functional for me but there was a race condition that arose. I haven't had time yet to properly fix and submit a PR. I hope to do it soon but am not sure when that will be.

**Comment by chrsmlls333** [comment]
Would it be possible in the meantime to add a second save() function that bundles the images, then clears the buffer? Then the next call does the same. This would allow us to call save manually, and get around the continuing Chrome crashes from long captures.

**Comment by spite** [comment]
Added autoSaveTime to CTarEncoder in v1.1.0
