### ISSUE TITLE
Sampling / Playback Speed

### ISSUE THREAD

**Issue by rankinstudio** [spite/ccapture.js#42]
I'm trying to get a smoother animation. Here are the settings I'm using. When I lower the framerate, the animation becomes too choppy, when I increase it, it plays back way too fast. How do I get better sampling and keep a good speed?

Thanks!

        var capturer = new CCapture( {
            framerate: 35,
            verbose: true,
            format: 'webm',
            quality: 80,
            name: 'MyVid',
            motionBlurFrames: 0   
        } );

**Comment by rankinstudio** [comment]
the step size is around 28ms. Can I get the step size to change but keep the FPS above 30?

**Comment by spite** [comment]
Without knowing more about your project, that's probably happening because your animation is frame-dependant. That is: if you increment your position 1 unit per frame, it will increment 60 units at 60FPS, 30 units at 30FPS and 960 units at 960FPS. 

You have to make your animations time dependant, that is: based on time. Calculate the delta time (time elapsed between the current frame and the last frame) and use that as a factor of your calculations.

Would that explain your problem?

**Comment by rankinstudio** [comment]
Thanks, got it figured out. My animations are based on time, just large time hops (orbits).

**Comment by evgeniyaaa** [comment]
Hello, I'm using [Createjs ](http://createjs.com/docs/easeljs/classes/Ticker.html) to create banner animations. I have a similar to the above mentioned problem: 

> When I lower the framerate, the animation becomes too choppy, when I increase it, it plays back way too fast

I think this is due to the [Ticker ](http://createjs.com/docs/easeljs/classes/Ticker.html) used to create the animations in Createjs.

The video works correctly when I set the framerate in the Ccapture to 60, but not on any other value.

If I set the framerate to 1 and the type to 'png' or 'jpg', then in the archive I still get around 60 images per second (not sure if this is related the above though).

Do you think that the Ticker is creating frame-dependent animations instead of time-dependent ones as you explained it above and that is causing the mix-up?

**Comment by spite** [comment]
As long as there's code somewhere that is adding per-frame (let's say `position = position + 1`) you're going to have this kind of problems. If that code was running correctly at 60FPS (position is incremented 60 times a second), it will run slower if the framerate is 30 (position will be incremented 30 times a second) or extremely fast if, for instance, you use the motion blur preset from ccapture (position will be incremented ~960 times a second).

The ways most libraries sync with time are intercepted by ccapture (setTimeout, setInterval, requestAnimationFrame, Date methods ,etc.). So from the libs perspective, time is running at exactly  the expected rate. 

Usually a speed problem would be in your animation loop, but there's precedent of weird stuff, like GreenSock's Tween library caching Date.now before ccapture can intercept it.

**Comment by evgeniyaaa** [comment]
Hi,

I think I understand what you are saying, but I'm still trying to figure
out how my animation behaves.

Thank you!
